#!/bin/bash
RTSP_URL_LIST_FILE=${1:-rtsp_url_list.txt}

# clear results file
RESULTSFILE="rtsp_test_results.txt"
> $RESULTSFILE

# temporary output file generated by test_rtsp_url.sh
TEMPOUT="rtsptest_temp_out.txt"


while read URL
do
  echo "_________________________"
  echo "testing url: $URL"
  echo ""
  ./test_rtsp_url.sh $URL
  echo ""
  valout=`cat $TEMPOUT | grep -c 'Freeing pipeline ...'`
  if [ "$valout" -eq "0" ]; then
    testresult="SUCCESS"
  else
    testresult="FAILURE"
  fi
  echo "Test Result: $testresult"
  echo -e "$URL\t$testresult" >> $RESULTSFILE

  # remove temp file from test_rtsp_url.sh
  rm $TEMPOUT

  echo ""
done < $RTSP_URL_LIST_FILE

echo ""
echo "________________________________________"
echo "end RTSP url file test"
echo "NOTE: this expects your file to have an empty line at the end"
echo "as last line will be ignored"
echo ""