version: "3.9"
services:

  ###### name service ######
  # (note: you can create multiple)
  gstdocker_service:

    #### name image  & container ####
    image: pwolfe854/${CONTAINER_NAME}:${ARCH}_${NOGPU}
    container_name: ${CONTAINER_NAME}

    #### command to keep container alive ####
    command: tail -F anything 

    #### build Dockerfile and pass build args ####
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FROM_IMG: ${FROM_IMG}
        GPU_ARG: ${GPU_ARG}
        POSE_REPO: https://github.com/pwolfe8/deepstream_pose_estimation
        POSE_REPO_SSH: git@github.com:pwolfe8/deepstream_pose_estimation.git
        POSE_REPO_FOLDER_NAME: deepstream_pose_estimation
        SSH_DEV: ${SSH_DEV}

    #### volumes and mappings ####
    volumes:
      ## volumes ##
      # - root:/root/
      # - consider adding the .engine models here after conversion for saving time on launch

      ## mappings ##
      - /tmp/.X11-unix/:/tmp/.X11-unix # x11
      - ./:${WORKDIR}/gitfoldermap # git folder map
      - ~/.ssh:/root/.ssh:ro # ssh folder from linux host

      ## device mappings ##
      - /dev/video0:/dev/video0 # for camera on video0 for example
      - /tmp/argus_socket:/tmp/argus_socket # map the argus_socket for csi cameras using nvarguscamerasrc

    #### environmental variables to set inside the container ####
    # environment:
    #   - DISPLAY=$DISPLAY
    #   PATH_ADD: /opt/nvidia/deepstream/deepstream-6.0/bin # you can append this to bashrc using dockerfile
      
    
    #### priveleged gains access to all devices on host ####
    # good for running docker inside docker if you need. also owning devices like /dev/video0
    privileged: true 

    #### configure docker network mode ####
    network_mode: "host" # uses host network stack
    
    #### runtime libraries ####
    # (like "nvidia" for docker gpu passthrough assuming nvidia-docker2 is installed on host)
    runtime: ${GPU_ARG}
    
    #### container directory to start in ####
    working_dir: ${WORKDIR}
    
#### create volumes here ####
# volumes:
#   root:
#   /opt/nvidia/deepstream/deepstream-6.0/samples/models/